### ISSUE TITLE
Use proper html & sign

### ISSUE THREAD

**Issue by sangjunp4rk** [jeremyjdz/prj-rev-bwfs-dasmoto#1]
Use the html & sign instead of just &, which is `&amp;`

https://github.com/jeremyjdz/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts%26Crafts/index.html#L5

**Comment by jeremyjdz** [comment]
I noticed that Atom marked them red.  I wasn't sure if that meant I was using incorrect code.  Thanks for the  correction.
