### ISSUE TITLE
Save images locally

### ISSUE THREAD

**Issue by sangjunp4rk** [jeremyjdz/prj-rev-bwfs-dasmoto#2]
You saved your images locally but don’t refer to them. Refer to the local images instead of online links. Saving and referring images adds to the stability of your website because your website is not reliant on the link to be valid all the time. So next time, save all the images under resources/images/

https://github.com/jeremyjdz/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts%26Crafts/index.html#L13

**Comment by jeremyjdz** [comment]
Yep i was having issues getting the images to load so I just went with the URL.  I am sure I wasn't mapping properly.  Tried to do some quick research but to decided to go with the links.
